services:
  postgis:
    image: postgis/postgis:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgis_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    env_file:
      - .env

  osm2pgsql:
    image: iboates/osm2pgsql:latest
    depends_on:
      - postgis
    environment:
      PGPASSWORD: ${POSTGRES_PASSWORD}
      PGUSER: ${POSTGRES_USER}
      PGDATABASE: ${POSTGRES_DB}
      PGPORT: 5432
      PGHOST: postgis
    volumes:
      - ./back-end:/data
      - ./osm-data:/osm-data
    env_file:
      - .env

  web:
    build: .
    container_name: django-docker
    ports:
      - "8000:8000"
    depends_on:
      - postgis
    volumes:
      - ./osm-data:/osm-data
      # - ./back-end:/app
    environment:
      DJANGO_SECRET_KEY: ${SECRET_KEY}
      DEBUG: ${DEBUG}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: postgis
      POSTGRES_PORT: 5432
      DJANGO_ALLOWED_HOSTS: ${SERVER_NAME}
    env_file:
      - .env

volumes:
  postgis_data:
