import { MENU_CONFIG } from "./menuConfig.js";
import { renderBlocks } from "./contentRenderer.js";
import { showBottomModal, updateBottomModalContent } from "../bottomModal.js";
import { MENU_TEXTS } from "../language.js";

export const displayMenuContent = (pageId) => {
  const content = document.getElementById(`seo-${pageId}`).innerHTML;
  updateBottomModalContent(`<div class="pico modal-div">${content}</div>`);
  showBottomModal({ authorizeMoveBehindModal: true, displayOnRight: true });
};
// Bridge for HTML onclick attributes
window.displayMenuContent = displayMenuContent;

export const initMenu = () => {
  const menuBox = document.getElementById("sideMenuContent");
  const seoContainer = document.getElementById("seo-content-pool");
  const checkbox = document.getElementById("menu__toggle");

  MENU_CONFIG.forEach((item) => {
    // Build the Menu Link
    const li = document.createElement("li");
    li.className = "menu__li";

    const a = document.createElement("a");
    a.className = "menu__item";
    a.innerText = MENU_TEXTS[item.labelKey];

    if (item.type === "link") {
      a.href = item.url;
      if (item.external) a.target = "_blank";
    } else {
      a.href = "#";
      a.addEventListener("click", (e) => {
        e.preventDefault();
        checkbox.checked = false; // Close menu
        displayMenuContent(item.id);
      });
    }
    li.appendChild(a);
    menuBox.appendChild(li);

    // Pre-render for SEO (Hidden in footer)
    if (item.type === "modal") {
      const section = document.createElement("section");
      section.id = `seo-${item.id}`;
      section.innerHTML = renderBlocks(item.content);
      seoContainer.appendChild(section);
    }
  });

  // Click Outside to Close
  document.addEventListener("click", (e) => {
    const burgerContainer = document.querySelector(".hamburger-menu");
    if (checkbox.checked && !burgerContainer.contains(e.target)) {
      checkbox.checked = false;
    }
  });

  /**
   * Global bridge to allow buttons generated by contentRenderer
   * to trigger new modals.
   */
  window.handleMenuAction = (actionId) => {
    // Try to find the pre-rendered SEO content we created in initMenu
    const targetContent = document.getElementById(`seo-${actionId}`);

    if (targetContent) {
      // If it exists in our menuConfig, open it
      updateBottomModalContent(`<div class="pico modal-div">${targetContent.innerHTML}</div>`);
      showBottomModal({ authorizeMoveBehindModal: true, displayOnRight: true });
    } else {
      // Custom logic for non-config actions if needed
      console.warn(`No content found for action: ${actionId}`);
    }
  };
};
