# Generated by Django 5.1.6 on 2025-02-18 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CameraTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True)),
                ('value', models.CharField(blank=True)),
                ('camera_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cameras.camera')),
            ],
        ),
    ]
