# Generated by Django 5.1.6 on 2025-02-22 00:38

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0002_cameratags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='surveillance',
            field=models.CharField(blank=True, choices=[('indoor', 'indoor'), ('outdoor', 'outdoor'), ('public', 'public'), ('transportation', 'transportation'), ('traffic', 'traffic'), ('red_light', 'red_light'), ('level_crossing', 'level_crossing'), ('speed_camera', 'speed_camera')]),
        ),
        migrations.CreateModel(
            name='CameraFocus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenario', models.CharField(choices=[('best', 'Best case scenario'), ('mean', 'Average'), ('worst', 'Worst case scenario')])),
                ('level', models.CharField(choices=[('identification', 'identification'), ('recognition', 'recognition'), ('observation', 'observation')])),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326)),
                ('camera_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cameras.camera')),
            ],
            options={
                'unique_together': {('camera_id', 'scenario', 'level')},
            },
        ),
    ]
