# Generated by Django 5.1.5 on 2025-02-02 02:49

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0002_building'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='focus',
            field=django.contrib.gis.db.models.fields.PolygonField(null=True, srid=4326),
        ),
    ]
