# Generated by Django 5.1.6 on 2025-02-22 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0003_alter_camera_surveillance_camerafocus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camera',
            name='focus',
        ),
    ]
