# Generated by Django 5.1.6 on 2025-02-23 17:49

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0004_remove_camera_focus'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='focus',
            field=django.contrib.gis.db.models.fields.PolygonField(null=True, srid=4326),
        ),
    ]
