# Generated by Django 5.1.6 on 2025-02-25 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0006_camera_buffer_max_vision'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='max_fov_distance',
            field=models.FloatField(null=True),
        ),
    ]
