# Generated by Django 5.1.6 on 2025-11-21 19:25

import os
from django.db import migrations

def load_sql_from_file(file_name):
    # Get the directory where this migration file exists
    migration_dir = os.path.dirname(__file__)
    # Navigate up one level to the app directory, then into the 'sql' folder
    sql_file_path = os.path.join(migration_dir, '../sql/', file_name)
    
    with open(sql_file_path, 'r') as f:
        return f.read()


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0007_camera_max_fov_distance'),
    ]

    operations = [
        migrations.RunSQL(
            sql=load_sql_from_file('tiles_functions.sql'),
        ),
    ]
