# Generated by Django 5.1.6 on 2025-11-26 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0008_add_tiles_sql_functions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camera',
            name='buffer_max_vision',
        ),
    ]
