# Generated by Django 5.1.6 on 2025-11-30 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0009_remove_camera_buffer_max_vision'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cameratags',
            unique_together={('camera_id', 'name')},
        ),
    ]
