# Generated by Django 5.1.6 on 2025-11-30 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0010_alter_cameratags_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camera',
            name='max_fov_distance',
        ),
    ]
