# Generated by Django 5.1.6 on 2025-12-01 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0011_remove_camera_max_fov_distance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tile',
            name='obj_count',
        ),
    ]
