# Generated by Django 5.1.6 on 2025-12-17 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0012_remove_tile_obj_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='camerafocus',
            name='with_intersection',
            field=models.BooleanField(default=False),
        ),
    ]
