# Generated by Django 5.1.6 on 2025-12-18 18:16

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0013_camerafocus_with_intersection'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='marker',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.functions.text.Concat(models.Case(models.When(models.Q(('surveillance_type', 'ALPR'), ('surveillance__in', ['red_light', 'level_crossing', 'speed_camera']), _connector='OR'), then=models.Value('traffic')), models.When(camera_type='fixed', then=models.Value('fixed')), models.When(camera_type='panning', then=models.Value('panning')), models.When(camera_type='dome', then=models.Value('dome')), default=models.Value(
                'cam')), models.Case(models.When(focus__isnull=True, then=models.Value('Missing')), models.When(models.Q(('mount', ''), ('surveillance_type', ''), ('camera_type', ''), ('zone', ''), ('height__isnull', True), models.Q(('camera_type', 'fixed'), ('angle__isnull', True)), models.Q(('camera_type', 'fixed'), ('direction__isnull', True)), _connector='OR'), then=models.Value('Incomplete')), default=models.Value('')), output_field=models.CharField()), output_field=models.CharField(max_length=20)),
        ),
    ]
