# Generated by Django 5.1.6 on 2025-12-18 18:16

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0013_camerafocus_with_intersection'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='color',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(surveillance='public', then=models.Value('Red')), models.When(surveillance='indoor', then=models.Value('Green')), models.When(surveillance='outdoor', then=models.Value('Blue')), default=models.Value('Black'), output_field=models.CharField()), output_field=models.CharField(max_length=10)),
        ),
        migrations.AddField(
            model_name='camera',
            name='marker',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(models.Q(('surveillance_type', 'ALPR'), ('surveillance__in', ['red_light', 'level_crossing', 'speed_camera']), _connector='OR'), then=models.Value('traffic')), default=django.db.models.functions.text.Concat(models.Case(models.When(camera_type='fixed', then=models.Value('fixed')), models.When(camera_type='panning', then=models.Value('panning')), models.When(camera_type='dome', then=models.Value('dome')), models.When(surveillance_type='guard', then=models.Value('guard')), default=models.Value('cam')), models.Case(models.When(surveillance='public', then=models.Value('Red')), models.When(surveillance='indoor', then=models.Value('Green')), models.When(surveillance='outdoor', then=models.Value('Blue')), default=models.Value('Black'), output_field=models.CharField())), output_field=models.CharField()), output_field=models.CharField(max_length=20)),
        ),
    ]
