# Generated by Django 6.0 on 2026-01-15 23:55

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0015_alter_camera_marker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='camera_type',
            field=models.CharField(blank=True, choices=[(
                'fixed', 'fixed'), ('panning', 'panning'), ('dome', 'dome'), ('panorama', 'panorama')]),
        ),
        migrations.RemoveField(
            model_name='camera',
            name='marker',
        ),
        migrations.AddField(
            model_name='camera',
            name='marker',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.functions.text.Concat(models.Case(models.When(models.Q(('surveillance_type', 'ALPR'), ('surveillance__in', ['red_light', 'level_crossing', 'speed_camera']), _connector='OR'), then=models.Value('traffic')), models.When(camera_type='fixed', then=models.Value('fixed')), models.When(camera_type='panning', then=models.Value('panning')), models.When(camera_type='dome', then=models.Value('dome')), models.When(camera_type='panorama', then=models.Value('pano')), default=models.Value('cam')), models.Case(models.When(models.Q(
                ('focus__isnull', True), models.Q(('surveillance_type', 'ALPR'), _negated=True)), then=models.Value('Missing')), models.When(models.Q(('mount', ''), ('surveillance_type', ''), models.Q(models.Q(('surveillance_type', 'ALPR'), _negated=True), ('camera_type', '')), ('zone', ''), ('height__isnull', True), models.Q(('camera_type', 'fixed'), ('angle__isnull', True)), models.Q(('camera_type', 'fixed'), ('direction__isnull', True)), _connector='OR'), then=models.Value('Incomplete')), default=models.Value('')), output_field=models.CharField()), output_field=models.CharField(max_length=20)),
        ),
    ]
